### ISSUE TITLE
Double issues: can t run the script

### ISSUE THREAD

**Issue by vincentBenet** [Dahlgren/python-pbo-fuse#1]
Hello @Dahlgren , I am running 2 issues to use your system when I am running on python 3.8

`C:\Users\vince>python D:\git\python-pbo-fuse\pbofuse.py D:\git\territory_conquest\TerritoryConquest - SERVER\territory_conquest
  File "D:\git\python-pbo-fuse\pbofuse.py", line 25
    st_mode=(S_IFDIR | 0755),
                          ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
`

`C:\Users\vince>python D:\git\python-pbo-fuse\pbofuse.py "D:\git\territory_conquest\TerritoryConquest - SERVER\territory_conquest"
Traceback (most recent call last):
  File "D:\git\python-pbo-fuse\pbofuse.py", line 9, in <module>
    from fuse import FUSE, FuseOSError, Operations, LoggingMixIn, fuse_get_context
  File "C:\Users\vince\AppData\Local\Programs\Python\Python38-32\lib\site-packages\fuse.py", line 115, in <module>
    raise EnvironmentError('Unable to find libfuse')
OSError: Unable to find libfuse`

The first problem can be fixed but not the missing package, it is unknow by pyPi and send me to [this git project](https://github.com/funkey/gunpowder)

`C:\Users\vince>pip install fuse
Collecting fuse
  Downloading fuse-0.1.2.tar.gz (18 kB)
ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
fuse depends on gunpowder@ git+https://github.com/funkey/gunpowder@721718b6569b47a2f5d5d6633c76c85f779e25c7`

**Comment by Dahlgren** [comment]
`libfuse` is not available on Windows, its a file system abstraction for Unix based systems.

Thankfully you can use my Dokan based PBO FS for Windows instead which offers the same functionality, https://github.com/Dahlgren/DokanPbo

**Comment by Vincentimetr** [comment]
Using Python 3.6.7 on Ubuntu for windows

![image](https://user-images.githubusercontent.com/38955854/76659935-03a75400-6578-11ea-9cf0-a9eadc032552.png)
